stages:
  - build
#  - test
  - deploy

build_job:
  stage: build
  script:
    - build/build.sh

#test_job:
#  stage: test
#  script:
#    - build/test.sh

#This job will be executed only on gitlab runners tagged with "docker-runner" and just for commits on branch "run"
deploy_job:
  stage: deploy
  script:
    - build/deploy.sh
  only:
    - deploy
  tags:
    - docker-run
